/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackToTop: typeof import('./components/common/backToTop.vue')['default']
    DefaultPage: typeof import('./components/common/defaultPage.vue')['default']
    Overlay: typeof import('./components/common/overlay.vue')['default']
    PageModal: typeof import('./components/common/pageModal.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
  }
}
